<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="ron" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width1" value="1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="width2" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.5" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.4" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <xacro:property name="wheelWidth" value="0.05"/>
  <xacro:property name="wheelRadius" value="0.1"/>
  <xacro:property name="wheelPos" value="0.2"/>
  <xacro:property name="wheelMass" value="1"/>

  <xacro:property name="casterRadius" value="0.05"/>
  <xacro:property name="casterMass" value="1"/>

  <xacro:property name="chassisHeight" value="0.5"/>
  <xacro:property name="chassisLength" value="0.8"/>
  <xacro:property name="chassisWidth" value="0.5"/>
  <xacro:property name="chassisMass" value="0.25"/>


  <xacro:property name="kinect_cam_py" value="-0.0125"/>
  <xacro:property name="cam_px" value="-0.087" />
<!--  <property name="cam_py" value="-0.0125" /> Y varies for different configurations. get sets in sensors_urdf -->
  <xacro:property name="cam_pz" value="0.2870" />
  <xacro:property name="cam_or" value="0" />
  <xacro:property name="cam_op" value="0" />
  <xacro:property name="cam_oy" value="0" />




  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find ron_description)/urdf/ron.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find ron_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find ron_description)/urdf/macros.xacro" />
  <!--xacro:include filename="$(find ron_description)/urdf/sensors/kinect.urdf.xacro"/-->


 <link name="base_link"/>

  <joint name="base_joint" type="fixed">
      <parent link="base_link"/>
      <child link="link1"/>
  </joint>

  <!--****************************************************************ALL BODY PARTS************************************************-->

  <!-- Link 1 -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2 + wheelRadius}" rpy="0 0 0"/>
      <geometry>
  <box size="${chassisWidth} ${chassisWidth} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2 + wheelRadius}" rpy="0 0 0"/>
      <geometry>
  <box size="${chassisWidth} ${chassisWidth} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <!--inertial>
      <origin xyz="0 0 ${height1/2 + wheelRadius}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (width1*width1 + height1*height1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (height1*height1 + width1*width1)}" iyz="0.0"
    izz="${mass / 12.0 * (width1*width1 + width1*width1)}"/>
    </inertial-->

    <inertial>
      <origin xyz="0 0 ${height1/2 + wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
   </link>


  <link name="caster_wheel">

    <collision>
      <origin xyz="${casterRadius-chassisWidth/2} 0 ${casterRadius}" rpy="0 0 0"/>
      <geometry>
  <sphere radius="${casterRadius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${casterRadius-chassisWidth/2} 0 ${casterRadius}" rpy="0 0 0"/>
      <geometry>
  <sphere radius="${casterRadius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${casterRadius-chassisWidth/2} 0 ${casterRadius}" rpy="0 0 0"/>
      <mass value="${casterMass}"/>
      <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
    </inertial>
  </link>

  <joint name="caster_link" type="fixed">
    <parent link="link1"/>
    <child link="caster_wheel"/>
  </joint>



  <link name="left_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
           <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
        </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
           <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
        </geometry>
            <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
      <mass value="${wheelMass}"/>
      <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
    </inertial>
  </link>



  <joint name="left_wheel_hinge" type="continuous">
    <parent link="link1"/>
    <child link="left_wheel"/>
    <origin xyz="${-wheelPos+chassisLength/2} ${-1*wheelWidth/2+-1*chassisWidth/2} ${wheelRadius}" rpy="0 0 0" />
    <axis xyz="0 1 0" rpy="0 0 0" />
          <!--limit effort="100" velocity="100"/-->
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>



  <link name="right_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
         <geometry>
           <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
         </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
         <geometry>
           <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
         </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
      <mass value="${wheelMass}"/>
      <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
    </inertial>
  </link>

  <joint name="right_wheel_hinge" type="continuous">
    <parent link="link1"/>
    <child link="right_wheel"/>
    <origin xyz="${-wheelPos+chassisLength/2} ${1*wheelWidth/2+1*chassisWidth/2} ${wheelRadius}" rpy="0 0 0" />
    <axis xyz="0 1 0" rpy="0 0 0" />
          <!--limit effort="100" velocity="100"/-->
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>


  <!-- Link 2 (Laser) -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 }" rpy="0 0 0"/>
      <geometry>
       <box size="${width2} ${width2} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 }" rpy="0 0 0"/>
      <geometry>
       <box size="${width2} ${width2} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 }" rpy="0 0 0"/>
      <mass value="${mass/100}"/>
      <inertia
    ixx="${mass / 120.0 * (width2*width2 + height2*height2)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 120.0 * (height2*height2 + width2*width2)}" iyz="0.0"
    izz="${mass / 120.0 * (width2*width2 + width2*width2)}"/>
    </inertial>
  </link>


  <joint name="joint1" type="fixed">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0.225 0 ${height1 + wheelRadius }" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0"/>
  </joint>


  <!--Link 3 Stationary camera-->

  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2 }" rpy="0 0 0"/>
      <geometry>
       <box size="${width2} ${width2} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 }" rpy="0 0 0"/>
      <geometry>
       <box size="${width2} ${width2} ${height3}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 }" rpy="0 0 0"/>
      <mass value="${mass/100}"/>
      <inertia
    ixx="${mass / 120.0 * (width2*width2 + height3*height3)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 120.0 * (height2*height2 + width2*width2)}" iyz="0.0"
    izz="${mass / 120.0 * (width2*width2 + width2*width2)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="fixed">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${height2 }" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0"/>
  </joint>

  <!--Link 4 Rotating camera-->


  <link name="link4">
    <collision>
      <origin xyz="0 0 ${height3/2 }" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${width2} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 }" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${width2} ${height3}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 }" rpy="0 0 0"/>
      <mass value="${mass/100}"/>
      <inertia
    ixx="${mass / 120.0 * (width2*width2 + height3*height3)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 120.0 * (height2*height2 + width2*width2)}" iyz="0.0"
    izz="${mass / 120.0 * (width2*width2 + width2*width2)}"/>
    </inertial>
  </link>



   <joint name="camera_hinge" type="continuous">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 ${height3 }" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0"/>
  </joint>





<!--****************************************************************ALL SENSORS************************************************-->

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
  <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ron_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${width2/2} 0 ${height2 - axel_offset/2}" rpy="0 0 0"/>
    <parent link="link2"/>
    <child link="hokuyo_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
  <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
  <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link} 0 ${height3 - axel_offset }" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="camera_link"/>
  </joint>


  <!-- Kinect -->
  <link name="kinect_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
  <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
  <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="kinect_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link} 0 ${height3 - axel_offset }" rpy="0 0 0"/>
    <parent link="link4"/>
    <child link="kinect_link"/>
  </joint>


<joint name="kinect_depth_joint" type="fixed">
  <origin xyz="0 0.028 0" rpy="0 0 0" />
  <parent link="kinect_link" />
  <child link="kinect_depth_frame" />
</joint>

<link name="kinect_depth_frame">
  <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
  </inertial>
</link>

<joint name="depth_optical_joint" type="fixed">
  <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
  <parent link="kinect_depth_frame" />
  <child link="kinect_depth_optical_frame" />
</joint>

<link name="kinect_depth_optical_frame">
  <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
  </inertial>
</link>


<!--****************************************************************CONTROL************************************************-->


  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="camera_hinge">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel_hinge">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel_hinge">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>
